name: money_mate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  flutter_bloc: ^9.1.1
  fl_chart: ^0.71.0
  shimmer: ^3.0.0
  uuid: ^4.3.3
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  go_router: ^13.2.0
  flutter_form_builder: ^10.0.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

