// Mocks generated by Mockito 5.4.5 from annotations
// in money_mate/test/features/summary/data/repositories/summary_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:money_mate/core/network/network_info.dart' as _i8;
import 'package:money_mate/features/summary/data/datasources/summary_datasource.dart'
    as _i5;
import 'package:money_mate/features/summary/data/models/summary_data_model.dart'
    as _i4;
import 'package:money_mate/features/summary/domain/entities/time_range.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAuth_1 extends _i1.SmartFake implements _i3.FirebaseAuth {
  _FakeFirebaseAuth_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSummaryDataModel_2 extends _i1.SmartFake
    implements _i4.SummaryDataModel {
  _FakeSummaryDataModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SummaryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSummaryRemoteDataSource extends _i1.Mock
    implements _i5.SummaryRemoteDataSource {
  MockSummaryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  _i3.FirebaseAuth get firebaseAuth => (super.noSuchMethod(
        Invocation.getter(#firebaseAuth),
        returnValue: _FakeFirebaseAuth_1(
          this,
          Invocation.getter(#firebaseAuth),
        ),
      ) as _i3.FirebaseAuth);

  @override
  _i6.Future<_i4.SummaryDataModel> getSummaryByTimeRange(
    _i7.TimeRange? timeRange, {
    String? userId,
    DateTime? referenceDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSummaryByTimeRange,
          [timeRange],
          {
            #userId: userId,
            #referenceDate: referenceDate,
          },
        ),
        returnValue:
            _i6.Future<_i4.SummaryDataModel>.value(_FakeSummaryDataModel_2(
          this,
          Invocation.method(
            #getSummaryByTimeRange,
            [timeRange],
            {
              #userId: userId,
              #referenceDate: referenceDate,
            },
          ),
        )),
      ) as _i6.Future<_i4.SummaryDataModel>);

  @override
  _i6.Future<_i4.SummaryDataModel> getSummaryByDateRange(
    DateTime? startDate,
    DateTime? endDate, {
    String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSummaryByDateRange,
          [
            startDate,
            endDate,
          ],
          {#userId: userId},
        ),
        returnValue:
            _i6.Future<_i4.SummaryDataModel>.value(_FakeSummaryDataModel_2(
          this,
          Invocation.method(
            #getSummaryByDateRange,
            [
              startDate,
              endDate,
            ],
            {#userId: userId},
          ),
        )),
      ) as _i6.Future<_i4.SummaryDataModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
